apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  type: ClusterIP #for internal connectivity within the cluster
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017